### PR TITLE
[WIP] modified for pgpg

### PR DESCRIPTION
**Pull request by diveshuttam**
This hasn't been tested yet will update in some time.

@dashohoxha 
I wanted to know something when I run `ds make` it does not install the scripts (i.e run `make install` in case of egpg) I have to manually run this in my case.
Am I missing something on my part. If I want to automate this also where should I add it? In my case I have added another install script.

### CODE REVIEW

**Review by dashohoxha — APPROVED** [review]
This looks good to me. I am merging it now, and later you can test and fix and improve it.

**Comment by dashohoxha** [comment]
The script that you have added seems OK to me. You should run it with `ds inject install.sh`. To do it automatically when the container is installed, you can add this command on the script `cmd/config.sh`.

However, since it is very simple you can also give the command `ds exec pip3 install --editable .` (this takes into account the the default workdir inside the container is `/host/pgpg`).

In case you need to change the directory, you can use a trick like this:
`ds exec bash -c "cd /host/pgp-1/ && pip3 install --editable ."`

**Comment by dashohoxha** [comment]
I just noticed that you also need to fix the README.md

**Comment by diveshuttam** [comment]
Thanks! I will test and update this command in readme also.
Also I'll  update the buster branch also in some time.

**Comment by diveshuttam** [comment]
Sorry couldn't update it yesterday as my ubuntu partition ran out of storage. It took quite some time for reconfiguring and partitioning.

**Pull request merged**
